### ISSUE TITLE
LCSC part numbers?

### ISSUE THREAD

**Issue by tlalexander** [will127534/StarlightEye#1]
Hello,
Do you by chance have LCSC part numbers for this board? Some of them are easy to figure out, but I started trying to find an equivalent part for the Hirose FFC connector and I realized I should just ask first.
Thanks!

**Comment by will127534** [comment]
check https://github.com/will127534/OneInchEye/blob/main/bom/BOM_JLCSMT.csv#L11
They are mostly the same.

I haven't send it to JLCPCB yet so don't have any part numbers to share yet.

**Comment by will127534** [comment]
Actually I probably want to open this until I have the design send to JLCPCB

**Comment by tlalexander** [comment]
Okay thanks!

**Comment by tlalexander** [comment]
Ah interesting that the Hirose connector is marked as discontinued on LCSC with no stock indicated.
https://www.lcsc.com/product-detail/FFC-FPC-Connectors_HRS-Hirose-FH12A-22S-0-5SH-55_C3168813.html
https://jlcpcb.com/partdetail/Hirose-FH12A_22S_0_5SH_55/C3168813

**Comment by will127534** [comment]
I guess you can swap it to a bottom-contact type: 
[https://www.lcsc.com/product-detail/FFC-FPC-Connectors_HRS-Hirose-FH12-22S-0-5SH-55_C597981.html](https://www.lcsc.com/product-detail/FFC-FPC-Connectors_HRS-Hirose-FH12-22S-0-5SH-55_C597981.html)

But then you will need a FPC cable with one contact on the top and the other on the bottom of the FPC

**Comment by will127534** [comment]
![image](https://github.com/will127534/StarlightEye/assets/6110733/092d7d1a-6e8a-4de6-8587-0d1dcaf975d4)

Some thing like this

**Comment by tlalexander** [comment]
Okay great, thank you for finding a suitable part! I have seen cables like that around, shouldn't be too much trouble thanks.

**Comment by phodina** [comment]
Hi @will127534 ,
speaking of the BOM and the parts - how do you solder the image sensor?

Do you let PCBWAY, JLCPCB or other manufacturer take care of that or do you solder the IMX585 IC yourself?

**Comment by will127534** [comment]
@phodina I use low temperature paste and heat the board from the bottom with either heatgun or IR PCB pre-heater.

**Comment by will127534** [comment]
Closing the issue with the updated design files
