### ISSUE TITLE
Simplifying Design

### ISSUE THREAD

**Issue by yhsyn0** [will127534/StarlightEye#11]
Hi, I want to customize and simplify the existing design with removing XVS, XHS, CLK_IN, XMASTER, ADDR0 and becuase I'm gonna use one sensor per device and thinking they are connected to each other but I'm not sure about sometings and have some questions. Also I don't want to use QWIIC. I'm asking questions assuming a few things, please correct me if I am wrong.

1- What XVS and XHS are doing ? If there aren't multiple sensor which need to be synchronized, are they necessary ? And what is the connection between XVS-XHS and Master-Slave ? I assume it will be used to synchronize the master with the slaves.
2- There is 24 MHz built-in oscillator.  When I look at the PCB picture in v1.4, I see that there is no external oscillator connected, so I assume that it can work without an extra clock source. How does it work if an external clock signal is given from the CLK_IN pin ?
3- According to the datasheet, multiple clock sources can be used, 24, 27, 37.125, 72 and 74.25 MHz. What are the advantages and disadvantages of higher clock speeds ? Can we count the FPS increase as one of them or does this only happen when using 8-lane instead of 4-lane ? Also, how many of these other clock speeds can the Raspberry Pi 5 handle ? lf I use a different clock source that the Raspberry Pi 5 can handle, all I need to do is change the part of the driver code related to the clock signal ?
4- What is the Master-Slave situation and what do XMASTER, ADDR0 and ADDR1 pins ?(Also I'm talking about i2c adress table on the board, what is default position, 0x1A) Again assuming that they are related to the use of multiple sensors, are they necessary if I'm gonna use one sensor and if there is no slave, am I the Master ? 
5- If I don't use any of these pins I mentioned, will it work ? 

I asked some things just to be sure. Thanks in advance for your answers.

**Comment by will127534** [comment]
1.  XVS and XHS are output or input sync signals, you can remove that.
2. I'm not quite sure what is your question here, the sensor require clock signal to work, so there is a oscillator on v1.4 board providing 24Mhz signal, you can send external 1.8V clock signal to that pin if you want to remove it.
3. I don't know, this is more for supporting systems that are already using those crystal in the systems so you can save one oscillator on the board. It does not change the sensor readout speed, the only thing you need to do is adjust the driver code to initialize the sensor with correct PLL settings.
4. I'm not clear about what are you asking, but these are not necessary for single sensor usage. The master option is for XHS/XVS clock output/input selection, which if not use then you can ignore them.
5. You can leave XHS,XVS, Master Open and pull the AD0 and AD1 to GND to fix I2C address to 0x1A.

**Comment by yhsyn0** [comment]
Thank you @will127534, you helped a lot. Maybe my questions were a bit confusing and not clear enough, but I got the answers I needed.
In the 2nd question, what I wanted to ask was what happens when an external oscillator is connected when there is already an internal oscillator. However, this question is just out of curiosity.
In the 4th question, I thought they had a relationship because the XMaster and ADD0-ADD1 pins were positioned close in the schematic, but now I realise that this is wrong.
Thank you again for your answers. I am currently working on a different sensor similar to the IMX585 based on your work.

**Comment by will127534** [comment]
> In the 2nd question, what I wanted to ask was what happens when an external oscillator is connected when there is already an internal oscillator. However, this question is just out of curiosity.

There is a resistor on the board to switch between the two options, so you either do external or internal with the HW.
