### ISSUE TITLE
STM8 or CH32

### ISSUE THREAD

**Issue by phodina** [will127534/StarlightEye#13]
Hi @will127534 ,
I checked the schematics and there's STM8 but all other READMEs and description mention the RISC-V processor.

What's the reason behind that inconsistency? Are these pin to pin compatible? 
Also why not go for STM32? Is that due to price or chip sourcing?

Also how flash the processor? Does it have a bootloader over the I2C pins?

The reason why I ask is I'd like to build the project and I'm scratching my head over this :-)

**Comment by will127534** [comment]
I just reused the STM8 footprints for CH32V003. There is no bootloader so you will have to flash it from the SWIO testpad on the board.
