### ISSUE TITLE
Could a IMX585-AAMJ1 work ?

### ISSUE THREAD

**Issue by martin-zs** [will127534/StarlightEye#16]
The IMX585-AAMJ1 is a monochrome 3840 (H) × 2160 (V); approx. 8.29M pixel;  Maximum frame rate in All-pixel scan mode: 12 bit: 60 frame/s, 10 bit: 90 frame/s.

My thinking was that with a monochrome sensor, I would only need to remove the glass window over the sensor (which absorbs UV)  and replace with a window made out of UV fused silica or fused quartz. That way I would not have to deal with removing the Bayer filter. Basically to use the 4K sensor with raw data for spectroscopy from ~220 to ~ 1250 nm. 

I'm was at the toying with the idea stage, when noticed your project and though that looks nearly perfect. Thanks in advance.

**Comment by will127534** [comment]
Hell yeah.
I've been using monochrome IMX585 with this project for a while now, the driver also supports monochrome with the `dtoverlay=imx585,mono` flag.

Here is my experiment with UV photography - though I think the lens itself is absorbing UV. 
![_DSC5555](https://github.com/user-attachments/assets/60d85913-9c6e-4233-b0d1-4a793db56fbe)

**Comment by will127534** [comment]
IMX585-AAMJ1= IMX585-AAQJ1 in terms of hardware (and actually software, just that you need to tell ISP that this is a monochrome sensor).

So if you can get the sensor then just drop it in.

**Comment by will127534** [comment]
For me I'm mostly using it for H-alpha solar imaging
![_DSC4266](https://github.com/user-attachments/assets/c07d42a7-f471-47fc-ae6d-cc0fd8ff82f6)

**Comment by martin-zs** [comment]
Absolutely perfect, thank you. That is music to my ears. I am moving at the moment, but once moved I know what I'll be doing. 

> So if you can get the sensor then just drop it in.
A quick search using "IMX585-AAMJ1 site:aliexpress.com", says that I probably can.
