### ISSUE TITLE
Where is the source code / driver

### ISSUE THREAD

**Issue by watchever** [will127534/StarlightEye#6]
Thanks a lot for this great project. This could be really interesting for a small project I am working on for astrophotography.
I am already working with an Arducam IMX462 sensor, but wondering where is the source code for the drivers on anything else for your sensor to be detected by Raspberry ? How do you communicate with the sensor ? Is it compatible with libcamera ?
Thanks

**Comment by watchever** [comment]
Hi Will, I have found the IMX585 driver on your repository, sorry for the lazy request.
https://github.com/will127534/imx585-v4l2-driver

However I still have some questions. 
What is max exposure for the sensor ? I have tried to reverse engineer the calculation in the IMX585 driver code source and found 8.4 sec, which sounds to be low for such a  light sensitive sensor, but my calculation is probably wrong. Can you tell me if I am wrong and if so what is max exposure ?

One more question, I guess that your dirver is libcamera compliant, but not so sure. Can you confirm ?

Thanks a lot for your help and great project. Really excited to try to build one of this and install it on raspberry.

I am working on a portable EEA system for astronomy, and if you are interested to cooperate, I will be more than happy to show you this project. Let me know.

Best

**Comment by will127534** [comment]
Hi @watchever No worries, sorry for the delayed response.

The exposure calculation is:
Integration Time [s] = [{VMAX × (SVR + 1) – (SHR)} × HMAX + offset] / (72 × 10^6)

In the driver I did not use SVR,  so the max exposure time is  VMAX_max (20bit) x HMAX_max(16bit) / 72Mhz (let's ignore all the offsets). Which is 954.4 seconds.

The driver is indeed libcamera compliant, you can actually follow my IMX283 quick start guide, just replace the imx283 driver link to imx585.

I have more updates to share in the next few days (new HW design/setup guide), please do check-in on this project later!

**Comment by will127534** [comment]
Quick question, what does EAA stands for?
I do see your(?) post here https://stargazerslounge.com/topic/401112-highly-portable-eea-device/

**Comment by watchever** [comment]
Hi Will, thanks a lot for your reply, EAA stands for Electronic Assisted Astronomy. In short use sensitive sensor to see in realtime really faint objects like nebulae, galaxies which are nearly impossible to see with unaided eyes even with large telescope. And also apply some specific image post processing dedicated to astronomy to enhance details, reduce sensor noise,... That's what you see on the project you quote (yes that's my post). My purpose was to build a very portable EAA system which doesn't need a separate camera, computer, screen and lot of wires. You just insert this small box in the eyepiece holder of your scope, control it through a wifi connection with your smartphone, tablet or any other devices and see nebulae, galaxies with full details and color. That's why the IMX585 is just perfect for such a project. The present version is based on raspberry pi 4 and I am working to migrate on Rpi5 for performance reasons because realtime image processing really needs velocity.

**Comment by will127534** [comment]
Just updated with the latest V1.6 design, tested with RPI5 along with a quick start guide.
We can move the discussion to [Discussions](https://github.com/will127534/StarlightEye/discussions).
